# Shared constants and enums for the Backup Manager addon

SHARED_FOLDER_NAME = "SharedConfigs"
OPERATION_BACKUP = "BACKUP"
OPERATION_RESTORE = "RESTORE"
OPERATION_DELETE = "DELETE_BACKUP"
OPERATION_SEARCH_BACKUP = "SEARCH_BACKUP"
OPERATION_SEARCH_RESTORE = "SEARCH_RESTORE"
