# Shared constants and enums for the Backup Manager addon

SHARED_FOLDER_NAME = "SharedConfigs"
OPERATION_BACKUP = "BACKUP"
OPERATION_RESTORE = "RESTORE"
OPERATION_SEARCH_BACKUP = "SEARCH_BACKUP"
OPERATION_SEARCH_RESTORE = "SEARCH_RESTORE"
OPERATION_DELETE_SELECTED_BACKUP = "DELETE_SELECTED_BACKUP"
OPERATION_DELETE_SELECTED_SHARED_BACKUP = "DELETE_SELECTED_SHARED_BACKUPS"
OPERATION_DELETE_ALL_BACKUPS = "DELETE_ALL_BACKUPS"
OPERATION_DELETE_ALL_SHARED_BACKUPS = "DELETE_ALL_SHARED_BACKUPS"
OPERATION_BATCH_BACKUP = "BATCH_BACKUP"
OPERATION_BATCH_RESTORE = "BATCH_RESTORE"
